# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/muir',
                'doc_host': 'https://aliceheiman.github.io',
                'git_url': 'https://github.com/aliceheiman/muir',
                'lib_path': 'muir'},
  'syms': {'muir.core': {'muir.core.foo': ('core.html#foo', 'muir/core.py')}}}
